// <auto-generated />
namespace MovieRentalApp_ASP.NET_MVC_ver2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PopulatingMembershipTypeNamesInDataBase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PopulatingMembershipTypeNamesInDataBase));
        
        string IMigrationMetadata.Id
        {
            get { return "201907171123252_PopulatingMembershipTypeNamesInDataBase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
